project:
  type: website
  output-dir: docs
  preview:
    port: 4202
  render:
    - "*.qmd" 
    - "!*.Rmd"

website:
  title: "Applied Predictive Modeling Blog"
  site-url: "https://blog.aml4td.org"
  comments: 
    utterances:
      repo: aml4td/blog
      label: utterances
      theme: body-light  
  navbar:
    right:
      - text: "Home"
        file: index.qmd
      - text: "Book"
        href: https://aml4td.org/
      - text: "Computing: R"
        href: https://tidymodels.aml4td.org/        
      - about.qmd
      - icon: github
        href: https://github.com/aml4td/blog

resources:
  - CNAME

format:
  html:
    toc: true
    theme: [simplex, includes/aml4td-blog.scss]
    mainfont: 'Libre Franklin'
    fig-width: 6
    fig-height: 4.25
    fig-align: center
    tbl-cap-location: bottom
    fig-cap-location: bottom
    keep-md: false
    highlight-style: arrow
    code-link: true
    code-block-bg: "#f9fafd"
    code-block-border-left: "#e1e7f6"
