---
title: "About"
---

The main contributors to this blog are Max Kuhn and Kjell Johnson. Together, they wrote the book [_Applied Predictive Modeling_](http://appliedpredictivemodeling.com/), which won the Ziegel award from the American Statistical Association, recognizing the best book reviewed in Technometrics in 2015. They have also co-written [_Feature Engineering and Selection_](https://bookdown.org/max/FES/). 

### Max Kuhn

Max Kuhn is a software engineer at [Posit PBC](https://posit.co/) (formerly known as RStudio Inc), where he is working on improving R’s modeling capabilities and maintaining about 30 packages, including [caret](https://cran.r-project.org/web/packages/caret/index.html) and [tidymodels](https://cran.r-project.org/web/packages/tidymodels/index.html). He has a Ph.D. in Biostatistics.  
 
Max was a Senior Director of Nonclinical Statistics at Pfizer Global R&D in Connecticut. He has applied models in the pharmaceutical and diagnostic industries for over 18 years. 

He is also the main author of [_Tidy Modeling with R_](https://www.tmwr.org/) and was the Drug Discovery Section Editor for [_Nonclinical Statistics for Pharmaceutical and Biotechnology Industries_](https://link.springer.com/book/10.1007/978-3-319-23558-5). 

Max can be found at: 

- [GitHub](https://github.com/topepo)
- [Twitter](https://twitter.com/topepos)
- [Mastodon](https://fosstodon.org/@topepo)
- [LinkedIn](https://www.linkedin.com/in/max-kuhn-864a9110)
- [Google Scholar](https://scholar.google.com/citations?user=TMDDykAAAAAJ&hl=en&oi=sra)


### Kjell Johnson

Kjell Johnson owns and founded [StatTenacity](https://www.stattenacity.com/). He has a Ph.D. in Statistics at the University of Kentucky and has contributed to drug discovery projects since 1999. He also enjoys making statistics accessible to non-statisticians. He teaches courses for scientists and statisticians alike, including short courses at the Society for Biomolecular Screening, the American Chemical Society, and the Deming Conference. 

Kjell is actively involved in other statistical service activities, including past activities of chairing the Midwest Biopharmaceutical Statistics Workshop Organizing Committee in 2010 and working on the ASA’s Biopharm Executive Committee.